### ISSUE TITLE
Error when building tests

### ISSUE THREAD

**Issue by dtroitskiy** [emaste/elftoolchain#4]
Hello. I'm on Ubuntu 14.04 and trying to build with pmake according to instructions in INSTALL.
All dependencies installed and everything's going fine until this:

all ===> test/libdwarf/ts/dwarf_init
cc -O2 -Wno-error -I../../../../test/tet/tet3.8/inc/tet3 -I/home/stranger/Library/elftoolchain/test/libdwarf/ts/common -I. -I/home/stranger/Library/elftoolchain/test/libdwarf/ts/dwarf_init -I../../../../common -I../../../../libdwarf -I../../../../libelf  -Wall -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wno-uninitialized -Wreturn-type -Wcast-qual -Wpointer-arith -Wwrite-strings -Wswitch -Wshadow -Werror   -c dwarf_init.c
In file included from dwarf_init.c:37:0:
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:481:1: error: function declaration isn’t a prototype [-

Werror=strict-prototypes]
 extern void (*tet_startup)();
 ^

And there are more error messages, I'll attach them as separate file.

**Comment by dtroitskiy** [comment]
Hmm, can't upload file for some reasons, so have to paste it directly:

../../../../test/tet/tet3.8/inc/tet3/tet_api.h:482:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 extern void (*tet_cleanup)();
 ^
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:486:2: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
  void (*testfunc)();
  ^
In file included from dwarf_init.c:44:0:
/home/stranger/Library/elftoolchain/test/libdwarf/ts/common/driver.c: In function ‘tet_invoketp’:
/home/stranger/Library/elftoolchain/test/libdwarf/ts/common/driver.c:239:13: error: passing argument 1 of ‘tet_printf’ discards ‘const’ qualifier from pointer target type [-Werror]
  tet_printf("Start Test Purpose <%s> on <%s>\n", tp->dtp->tp_name,
             ^
In file included from dwarf_init.c:37:0:
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:376:22: note: expected ‘char *’ but argument is of type ‘const char *’
 TET_IMPORT_FUNC(int, tet_printf, TET_PROTOLIST((char *, ...)));
                      ^
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:209:25: note: in definition of macro ‘TET_IMPORT_FUNC’
  TET_IMPORT extern TYPE NAME ARGS
                         ^
dwarf_init.c: In function ‘tp_dwarf_init’:
dwarf_init.c:58:14: error: passing argument 1 of ‘tet_printf’ discards ‘const’ qualifier from pointer target type [-Werror]
   tet_printf("open %s failed: %s", _cur_file, strerror(errno));
              ^
In file included from dwarf_init.c:37:0:
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:376:22: note: expected ‘char *’ but argument is of type ‘const char *’
 TET_IMPORT_FUNC(int, tet_printf, TET_PROTOLIST((char *, ...)));
                      ^
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:209:25: note: in definition of macro ‘TET_IMPORT_FUNC’
  TET_IMPORT extern TYPE NAME ARGS
                         ^
dwarf_init.c:64:14: error: passing argument 1 of ‘tet_printf’ discards ‘const’ qualifier from pointer target type [-Werror]
   tet_printf("dwarf_init failed: %s", dwarf_errmsg(de));
              ^
In file included from dwarf_init.c:37:0:
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:376:22: note: expected ‘char *’ but argument is of type ‘const char *’
 TET_IMPORT_FUNC(int, tet_printf, TET_PROTOLIST((char *, ...)));
                      ^
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:209:25: note: in definition of macro ‘TET_IMPORT_FUNC’
  TET_IMPORT extern TYPE NAME ARGS
                         ^
dwarf_init.c:70:16: error: passing argument 1 of ‘tet_infoline’ discards ‘const’ qualifier from pointer target type [-Werror]
   tet_infoline("dwarf_init didn't return DW_DLV_ERROR when"
                ^
In file included from dwarf_init.c:37:0:
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:372:23: note: expected ‘char *’ but argument is of type ‘const char *’
 TET_IMPORT_FUNC(void, tet_infoline,  TET_PROTOLIST((char *)));
                       ^
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:209:25: note: in definition of macro ‘TET_IMPORT_FUNC’
  TET_IMPORT extern TYPE NAME ARGS
                         ^
In file included from dwarf_init.c:36:0:
/home/stranger/Library/elftoolchain/test/libdwarf/ts/common/driver.h:55:14: error: passing argument 1 of ‘tet_printf’ discards ‘const’ qualifier from pointer target type [-Werror]
   tet_printf("dwarf_finish failed: %s",   \
              ^
dwarf_init.c:80:2: note: in expansion of macro ‘TS_DWARF_FINISH’
  TS_DWARF_FINISH(dbg, de);
  ^
In file included from dwarf_init.c:37:0:
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:376:22: note: expected ‘char *’ but argument is of type ‘const char *’
 TET_IMPORT_FUNC(int, tet_printf, TET_PROTOLIST((char *, ...)));
                      ^
../../../../test/tet/tet3.8/inc/tet3/tet_api.h:209:25: note: in definition of macro ‘TET_IMPORT_FUNC’
  TET_IMPORT extern TYPE NAME ARGS
                         ^
cc1: all warnings being treated as errors
*** Error code 1

Stop.
pmake[4]: stopped in /home/stranger/Library/elftoolchain/test/libdwarf/ts/dwarf_init
*** Error code 1

Stop.
pmake[3]: stopped in /home/stranger/Library/elftoolchain/test/libdwarf/ts
*** Error code 1

Stop.
pmake[2]: stopped in /home/stranger/Library/elftoolchain/test/libdwarf
*** Error code 1

Stop.
pmake[1]: stopped in /home/stranger/Library/elftoolchain/test
*** Error code 1

Stop.

**Comment by emaste** [comment]
Ubuntu 18.04 is now in CI and passing, so I'll close this issue.

**Comment by dtroitskiy** [comment]
Pandon my irony, but wow that was fast =)
After 5 years of course I have no idea what was that about.
